CREATE TABLE ALBUM(
  AlbumID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  AlbumName CHAR(50) NOT NULL,
  AlbumSales INT NOT NULL );

CREATE TABLE TRACK(
  TrackID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  TrackName CHAR(100) NOT NULL,
  TrackGenre CHAR(100) NOT NULL,
  Duration INT NOT NULL,
  ReleaseDate DATE NOT NULL,
  AlbumID INT NOT NULL,
  CONSTRAINT AL_TRACK_FK FOREIGN KEY(AlbumID)
  REFERENCES ALBUM(AlbumID)
  ON UPDATE CASCADE
  ON DELETE CASCADE );

CREATE TABLE MEDIA (
  MediaID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  TrackVideoClip CHAR(3) NOT NULL,
  VideoClipViews INT NULL,
  SpotifyStreams INT NOT NULL,
  USAPeak INT NULL,
  TrackID INT NOT NULL,
  CONSTRAINT TRACK_MEDIA_FK FOREIGN KEY(TrackID)
  REFERENCES Track(TrackID)
  ON UPDATE CASCADE
  ON DELETE CASCADE );
