INSERT INTO ALBUM VALUES ('Short n'' Sweet', 342500);
INSERT INTO ALBUM VALUES ('emails i can''t send',77500);
INSERT INTO ALBUM VALUES ('Singular: Act II', 30000);
INSERT INTO ALBUM VALUES ('Singular: Act I', 40000);
INSERT INTO ALBUM VALUES ('EVOLution', 45000);
INSERT INTO ALBUM VALUES ('Eyes Wide Open', 40000);
